
// user actions
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOAD_ERROR = 'USER_LOAD_ERROR';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// patient actions
export const PATIENT_LIST_LOADING = 'PATIENT_LIST_LOADING';
export const PATIENT_LIST_LOADED = 'PATIENT_LIST_LOADED';
export const PATIENT_LIST_LOAD_ERROR = 'PATIENT_LIST_LOAD_ERROR';

export const PATIENT_EVERYTHING_CLEAR = 'PATIENT_EVERYTHING_CLEAR';
export const PATIENT_EVERYTHING_LOADING = 'PATIENT_EVERYTHING_LOADING';
export const PATIENT_EVERYTHING_LOADED = 'PATIENT_EVERYTHING_LOADED';
export const PATIENT_EVERYTHING_LOAD_ERROR = 'PATIENT_EVERYTHING_LOAD_ERROR';